### ISSUE TITLE
Verbindungs Probleme zum Server

### ISSUE THREAD

**Issue by csBlackWolf** [csBlackWolf/minefox#3]
Aufgrund einer technischen Störung bei verschiedenen Providern, scheint der Server für manche Nutzer ab und an nicht erreichbar zu sein, obwohl dieser störungsfrei läuft.
Grund dafür sind Schäden an der Anbindung des Servers, die durch den gestrigen Sturm hier zu Orte entstanden sind.

Es wird dran gearbeitet die Schäden zu beseitigen, jedoch kann sich dies aufgrund des wechselhaften Wetters und spontan auftretenden stärkeren Windes, noch etwas hinziehen.

Wir bitten um etwas Geduld.

---
Mit freundlichen Grüßen

Das Team von MineFox.Fun

**Comment by KiyoFurball** [comment]
Because of some technical difficulties with different providers can the server be shown as not available, even tho it seems like it works fine.
Reason behind it are some damages on some lines between the providers, because of the heavy storm currently in Germany.

They are working to fix the issues but, because the weather is still rainy and very windy it can take a while.

Please be patient.
